export default {
	PODIE: 'Podie',
	LOGIN: 'Login',
	LOGIN_GITHUB: 'Login GitHub',
	LOGIN_GCP: 'Login GCP',
	LOGOUT: 'Logout',
	LET_US_KNOW: 'Let us know',
	EMAIL: 'Email',
	NOTIFY_ME: 'Notify me',
	GITHUB: 'Github',
	AVATAR: 'Avatar',
	WORKSPACES: 'Workspaces',
	UNDER_CONSTRUCTION: '...under contruction...',
	TITLE: 'Remote dev | Podie',
	DESCRIPTION: 'Remote dev environment without containerize overhead 👍.',
	KEYWORDS: [
		'Remote',
		'Development',
		'GCP',
		'AWS',
		'Github',
		'Container',
		'Azure'
	],
	INSTANCE: 'Instance',
	OOPS: 'Oops. Something went wrong!',
	CONNECT_GCP: 'Connect GCP',
	REPOES: 'Repoes',
	REPO: 'Repo',
	PROJECTS: 'Projects',
	SELECT_PROJECT: 'Select project',
	CONFIRM: 'Confirm',
	NAME: 'Name',
	IMAGE: 'Image',
	IP: 'Ip',
	ADDRESS: 'Address',
	DELETE: 'Delete',
	CREATE_INSTANCE: 'Create instance',
	CREATE_IMAGE: 'Create image',
	REGIONS: 'Regions',
	REGION: 'Region',
	ZONE: 'Zone',
	MACHINE_TYPE: 'Machine type',
	REFRESH: 'Refresh',
	DISK_SIZE: 'Disk size (GB)',
	SSH_KEYS: 'SSH keys',
	STARTUP: 'Startup command',
	DOCKER_IMAGE: 'Docker image',
	BRANCH: 'Branch',
	KEY: 'Key',
	ADD: 'Add',
	NEW_KEY: 'New key',
	VALUE: 'Value',
	INSTANCES: 'Instances',
	IMAGES: 'Images',
	PRIVACY_POLICY: 'Privacy Policy',
	TERMS_AND_CONDITIONS: 'Terms and Conditions',
	TERMINATE: 'Terminate',
	MACHINES: 'Machines',
	TERMINATED: 'Terminated',
	ACTION: 'Action',
	START: 'Start',
	START_FROM_IMAGE: 'Start from image',
	REFRESHING: 'Refreshing',
	PROFILE: 'Profile',
	SAVE: 'Save',
	SUBMITING: 'Submiting...',
	DELETING: 'Deleting...',
	CONTINUE_WITH_GITHUB: 'Continue with Github',
	INTEGRATIONS: 'Integrations',
	GCP_PROJECT_ID: 'GCP Project id',
	GOOGLE_IAM: 'Google Console IAM',
	GOOGLE_CLOUD: 'Google cloud',
	NEW_GCP_PROJECT: 'New Google Cloud project',
	FROM_INSTANCE: 'From instance',
	CREATE: 'Create',
	STATUS: 'Status',
	UPDATE: 'Update',
	CHANGE_MACHINE_TYPE: 'Change machine type',
	NEXT: 'Next'
};
