export default {
	PODIE: 'Podie',
	LOGIN: 'Login',
	LOGIN_GITHUB: 'Login GitHub',
	LOGIN_GCP: 'Login GCP',
	LOGOUT: 'Logout',
	LET_US_KNOW: 'Let us know',
	EMAIL: 'Email',
	NOTIFY_ME: 'Notify me',
	GITHUB: 'Github',
	AVATAR: 'Avatar',
	WORKSPACES: 'Workspaces',
	UNDER_CONSTRUCTION: '...under contruction...',
	TITLE: 'Remote dev | Podie',
	DESCRIPTION:
		"It's a bit like Gitpod.io and Codespace. You pick repo, choose machine type, region and KABOOM! 👍.",
	KEYWORDS: [
		'Remote',
		'Development',
		'GCP',
		'AWS',
		'Github',
		'Container',
		'Azure'
	],
	OOPS: 'Oops. Something went wrong!',
	CONNECT_GCP: 'Connect GCP',
	REPOES: 'Repoes',
	PROJECTS: 'Projects',
	SELECT_PROJECT: 'Select project',
	CONFIRM: 'Confirm',
	NAME: 'Name',
	IP: 'Ip',
	STATUS: 'Status',
	DELETE: 'Delete'
};
