export default {
	PODIE: 'Podie',
	LOGIN: 'Login',
	LOGIN_GITHUB: 'Login GitHub',
	LOGIN_GCP: 'Login GCP',
	LOGOUT: 'Logout',
	LET_US_KNOW: 'Let us know',
	EMAIL: 'Email',
	NOTIFY_ME: 'Notify me',
	GITHUB: 'Github',
	AVATAR: 'Avatar',
	WORKSPACES: 'Workspaces',
	UNDER_CONSTRUCTION: '...under contruction...',
	TITLE: 'Remote dev | Podie',
	DESCRIPTION:
		"It's a bit like Codespace but run on your own GCP, like Gitpod but don't need to setup 👍.",
	KEYWORDS: [
		'Remote',
		'Development',
		'GCP',
		'AWS',
		'Github',
		'Container',
		'Azure'
	],
	OOPS: 'Oops. Something went wrong!',
	CONNECT_GCP: 'Connect GCP',
	REPOES: 'Repoes',
	REPO: 'Repo',
	PROJECTS: 'Projects',
	SELECT_PROJECT: 'Select project',
	CONFIRM: 'Confirm',
	NAME: 'Name',
	IP: 'Ip',
	STATUS: 'Status',
	DELETE: 'Delete',
	CREATE_INSTANCE: 'Create instance',
	REGIONS: 'Regions',
	REGION: 'Region',
	ZONE: 'Zone',
	MACHINE_TYPE: 'Machine type',
	REFRESH: 'Refresh',
	DISK_SIZE: 'Disk size (GB)',
	SSH_KEYS: 'SSH keys',
	STARTUP: 'Startup command',
	BRANCH: 'Branch',
	KEY: 'Key',
	ADD: 'Add',
	SSH_KEYS_LIMIT:
		"Can't have more than 4 ssh_keys because of max cookie size 😥",
	NEW_KEY: 'New key',
	VALUE: 'Value',
	INSTANCES: 'Instances',
	PRIVACY_POLICY: 'Privacy Policy',
	TERMS_AND_CONDITIONS: 'Terms and Conditions'
};
